/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.27
 * Generated at: 2019-12-12 07:27:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- 회원가입 페이지 -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\twindow.onload = function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction appendYear() {\r\n");
      out.write("\t\t\tvar date = new Date();\r\n");
      out.write("\t\t\tvar year = date.getFullYear();\r\n");
      out.write("\t\t\tvar selectValue = document.getElementById(\"year\");\r\n");
      out.write("\t\t\t//var selectValue = document.regFrm.year;\r\n");
      out.write("\t\t\tvar optionIndex = 0;\r\n");
      out.write("\t\t\tfor (var i = year - 100; i <= year; i++) {\r\n");
      out.write("\t\t\t\tselectValue.add(new Option(i, i), optionIndex++);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tfor (var i = 0; i <= 100; i++) {\r\n");
      out.write("\t\t\t\t if(selectValue.options[i].value=='1982'){\r\n");
      out.write("\t\t\t\t\tselectValue.options[i].selected = true;\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction appendMonth() {\r\n");
      out.write("\t\t\tvar selectValue = document.getElementById(\"month\");\r\n");
      out.write("\t\t\tvar optionIndex = 0;\r\n");
      out.write("\t\t\tfor (var i = 1; i <= 12; i++) {\r\n");
      out.write("\t\t\t\tselectValue.add(new Option(i, i), optionIndex++);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction appendDay() {\r\n");
      out.write("\t\t\tvar selectValue = document.getElementById(\"day\");\r\n");
      out.write("\t\t\tvar optionIndex = 0;\r\n");
      out.write("\t\t\tfor (var i = 1; i <= 31; i++) {\r\n");
      out.write("\t\t\t\tselectValue.add(new Option(i, i), optionIndex++);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tappendYear();\r\n");
      out.write("\t\tappendMonth();\r\n");
      out.write("\t\tappendDay();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t//이메일 입력방식 선택 \r\n");
      out.write("\t\t$('#selectEmail').change(function() {\r\n");
      out.write("\t\t\t$(\"#selectEmail option:selected\").each(function() {\r\n");
      out.write("\t\t\t\tif ($(this).val() == '1') { //직접입력일 경우 \r\n");
      out.write("\t\t\t\t\t$(\"#str_email02\").val(''); //값 초기화 \r\n");
      out.write("\t\t\t\t\t$(\"#str_email02\").attr(\"readOnly\", false); //활성화 \r\n");
      out.write("\t\t\t\t} else { //직접입력이 아닐경우 \r\n");
      out.write("\t\t\t\t\t$(\"#str_email02\").val($(this).text()); //선택값 입력\r\n");
      out.write("\t\t\t\t\t$(\"#str_email02\").attr(\"readOnly\", true); //비활성화\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>부산여행갑시다 그럽시다</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table{\r\n");
      out.write(" border-spacing: 5px 5px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<!-- <iframe name=\"ifm\" style=\"width: 0; height: 0;\"></iframe> -->\r\n");
      out.write("\t\t<form name=\"regFrm\" method=\"post\" action=\"joinProc.jsp\">\r\n");
      out.write("\t\t\t<table id=\"tbl1\" cellpadding=\"3\" style=\"width: 440px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\" align=\"center\">회&nbsp;원&nbsp;가&nbsp;입</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr></tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>아이디</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input name=\"id\" > \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\"\t value=\"중복 확인\" onclick=\"javascript:idCheck(this.form.id.value)\">\r\n");
      out.write("\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"pwd\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" name=\"repwd\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이름</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"name\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>생년월일</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t <select id=\"year\" name=\"year\" style=\"width: 100px;\"></select> 년&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<select id=\"month\" name=\"month\" style=\"width: 50px;\"></select> 월&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<select id=\"day\" name = \"day\" style=\"width: 50px;\"></select>일\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>성별</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><select name=gender>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\" selected>선택하세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"male\">남성</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"female\">여성</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>이메일</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"str_email01\" id=\"str_email01\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 130px\"> @ <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"str_email02\" id=\"str_email02\" style=\"width: 150px;\" readOnly\r\n");
      out.write("\t\t\t\t\t\tvalue=\"naver.com\">\r\n");
      out.write("\t\t\t\t\t\t <select style=\"width: 150px; margin-right: 10px\" name=\"selectEmail\"\r\n");
      out.write("\t\t\t\t\t\tid=\"selectEmail\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"naver.com\" selected>naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>주소</td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"zipcode\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"  우편번호 검색  \" onclick=\"zipSearch()\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"address1\" size=\"45\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><input name=\"address2\" size=\"45\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\">개인정보 취급방침</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><textarea name=\"privacy\" style=\"width: 100%\" rows=\"5\"\r\n");
      out.write("\t\t\t\t\t\t\tcols=\"40\" disabled=\"disabled\">\r\n");
      out.write("\t\t\t1. 개인정보의 처리 목적 <부산여행>(‘busan’이하 ‘부산여행’) 은(는) 다음의 목적을 위하여 개인정보를 처리하고 있으며, 다음의 목적 이외의 용도로는 이용하지 않습니다.\r\n");
      out.write("- 고객 가입의사 확인, 고객에 대한 서비스 제공에 따른 본인 식별.인증, 회원자격 유지.관리, 물품 또는 서비스 공급에 따른 금액 결제, 물품 또는 서비스의 공급.배송 등\r\n");
      out.write("\r\n");
      out.write("\t\t\t</textarea></td>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><input type=\"radio\" name=\"privacy\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"1\">동의합니다 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\ttype=\"radio\" name=\"privacy\" value=\"2\" checked=\"checked\">동의하지\r\n");
      out.write("\t\t\t\t\t\t않습니다</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"center\"><br /> <input type=\"button\" id=\"btn1\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"회&nbsp;원&nbsp;가&nbsp;입\" onclick=\"inputCheck()\">\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
